/**
 * Every word the clinical AI surface says.
 *
 * Copy lives in one file, as in every feature since Phase 03, so a clinician
 * can review the wording without reading React — and here that matters more
 * than usual, because these sentences are the disclosure
 * `docs/HEALTHCARE_AND_AI_SAFETY.md` section 7 requires: visible and plain,
 * never a tooltip and never a footnote.
 *
 * ## The three things a reader must always be able to see
 *
 *   1. that this is AI-generated (section 82);
 *   2. that it has not been checked by a clinician (section 82);
 *   3. that the practitioner decides (sections 3, 40).
 *
 * They are not one sentence in a header that scrolls away. The label sits on
 * the result itself, the disclaimer sits above it, and the "not clinician
 * verified" badge is attached to the output rather than to the panel — because
 * the output is the part somebody copies.
 */

export const CLINICAL_AI_COPY = {
  /** The panel's own heading. Not "AI Assistant", not a product name. */
  heading: "AI clinical support",
  navLabel: "AI support",
  backLabel: "Back to consultation",

  intro:
    "Generates a structured summary or a set of points for you to consider, from the clinical information you select below. It is a documentation aid, not a second opinion.",

  /**
   * The standing disclaimer (sections 3, 40).
   *
   * Section 3 offers wording; this says the same things in the plainest form
   * that fits above a control a practitioner uses several times a day.
   */
  disclaimer: {
    title: "This is assistance, not clinical judgment",
    body: "Everything below is generated by an AI model and may be incomplete or wrong. It does not diagnose, does not prescribe, and makes no clinical decision. Check every point against the record and your own judgment before acting on it.",
  },

  contextHeading: "What to include",
  contextDescription:
    "Only what you select here is sent. The patient's name, contact details and date of birth are never sent.",

  contextOptions: {
    history: {
      label: "Previous consultations you recorded",
      description:
        "Up to three of your own most recent completed consultations with this patient.",
    },
    prescriptions: {
      label: "Previously issued prescriptions",
      description: "Up to three, with their items.",
    },
    treatmentPlans: {
      label: "Treatment plans",
      description: "Up to two active or completed plans.",
    },
    documents: {
      label: "Document titles",
      description:
        "Titles and dates only. File contents are never read or sent — Punarvasu does not extract text from uploaded documents.",
    },
  },

  taskHeading: "What to generate",
  generateLabel: "Generate",
  generatingLabel: "Generating…",
  cancelLabel: "Cancel",
  regenerateLabel: "Regenerate",
  dismissLabel: "Dismiss",
  copyLabel: "Copy",
  copiedLabel: "Copied",

  /** Section 81. Says what is happening, and claims nothing clinical. */
  loading: "Analysing the clinical information you selected…",
  loadingRegionLabel: "AI assistance status",

  resultHeading: "AI-generated result",
  /** Sections 24, 82. Attached to the output, not to the page. */
  generatedBadge: "AI-generated",
  unverifiedBadge: "Not clinician verified",

  sectionHeadings: {
    summary: "Summary",
    considerations: "Points to consider",
    missingInformation: "Potentially missing information",
    warnings: "Review required",
  },

  /** Sections 41, 132. Source data, distinguished from generated text. */
  sourcesHeading: "Based on",
  sourcesNote:
    "Only Punarvasu's own records for this patient were used. No external guideline, study or medical database was consulted.",

  /**
   * The not-persisted notice (sections 25, 28, 84).
   *
   * Said out loud because a practitioner who assumes it is saved will navigate
   * away and lose it, and because "is this in the patient's record?" must have
   * an unambiguous answer.
   */
  ephemeralNotice:
    "This result is not saved. It is not part of the patient's record and will be gone when you leave this page. If any of it is useful, write it in your own words in the consultation notes.",

  /** Sections 84-85, 140. */
  staleNotice: {
    title: "The clinical information has changed",
    body: "This result was generated before the consultation was last edited, so it no longer reflects what is recorded. Regenerate it before relying on any of it.",
  },

  /** Section 87. Shown beside the copy control. */
  copyNotice:
    "Copied text is AI-generated and unverified. Read and rewrite it in your own words before it goes anywhere near the clinical record.",

  usageLabel: (used: number, allowed: number, minutes: number) =>
    `${used} of ${allowed} AI requests used in the last ${minutes} minutes.`,

  /* --------------------------------------------------------------------- */
  /* Unavailable states — four, because four different things are wrong     */
  /* --------------------------------------------------------------------- */

  notConfigured: {
    title: "AI support is not switched on",
    body: "This clinic has not enabled AI clinical support. Everything else in the consultation works normally.",
  },

  noPractitionerRecord: {
    title: "AI support is not available for this account",
    body: "This account is not linked to a practitioner record on the clinic's roster. Ask an administrator to set one up.",
  },

  unavailable: {
    title: "AI support is temporarily unavailable",
    body: "Your consultation is unaffected and can be continued normally.",
  },

  notFound: {
    title: "We couldn't find that appointment",
    body: "It may have been changed, or it may belong to another practitioner.",
  },

  emptyResult: {
    title: "Nothing generated yet",
    body: "Choose what to include and what to generate, then select Generate.",
  },

  /**
   * The boundary, stated where a practitioner might otherwise look for a
   * control that does not exist (sections 72, 109).
   *
   * The convention every phase of this project has followed: say what is
   * deliberately absent, in the place somebody would look for it.
   */
  boundaryNotice: {
    title: "What this tool will not do",
    body: "There is no way to apply any of this to a prescription, a treatment plan or the clinical record. Nothing here writes anything. If something below is useful, you write it yourself in the consultation notes, in your own words, and you remain responsible for it.",
  },
} as const;
