import "server-only";

import {
  DOCUMENT_BUCKET,
  SIGNED_URL_TTL_SECONDS,
  type AllowedMimeType,
} from "@/config/documents";
import { logger } from "@/lib/logging/logger";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { createSupabaseServerClient } from "@/lib/supabase/server";

/**
 * The storage adapter: the only module in the application that names the
 * bucket or touches an object.
 *
 * ## Two clients, and the split is deliberate
 *
 * ```text
 * write   the service-role client, after the server has authorized
 * read    the caller's OWN client, under the storage select policy
 * ```
 *
 * **Writes.** There is no insert policy on the bucket for any client role,
 * so nothing a browser holds can put an object into it. That is the point: a
 * client that could write could choose its own path, which sections 8 and 61
 * forbid. The object key is generated by the server from a patient id it
 * resolved and a document id it minted, after it has read the bytes and
 * confirmed what they are. `phase_14.md` section 59 permits the service-role
 * key exactly here — a trusted server environment, for an operation that
 * cannot be expressed as the user's own action — and `lib/supabase/admin.ts`
 * requires every call site to have authorized first, which the upload route
 * does before it reaches this module.
 *
 * **Reads.** Minted with the *caller's own* client, so
 * `patient_documents_objects_select` decides. If the application ever forgot
 * a check, storage would still refuse: the policy resolves the object key
 * back to its document row and applies the same rule row-level security
 * applies to the row itself. Using the service role here would have thrown
 * that away — it bypasses every policy — so it is not used for reads, and a
 * test asserts the admin client appears in this file's write paths only.
 *
 * ## What never leaves this module
 *
 * A provider error. Supabase's storage errors name the bucket and sometimes
 * the key; both are discarded, and the caller gets `null` or `false` plus a
 * safe sentence of its own (sections 50, 75 and example 9).
 *
 * ## What is never logged
 *
 * A storage path, a signed URL, a filename or a title. A log line here
 * carries the operation and the actor's opaque id, and — because a document
 * id is a uuid that means nothing on its own — the document id.
 */

export interface UploadedObject {
  readonly path: string;
}

/**
 * Puts the validated bytes at the server-generated key.
 *
 * `upsert: false` is load-bearing (section 37): an object is written once
 * and never overwritten, so a corrected report can only ever be a **new**
 * document. Combined with the unique `storage_path` and a fresh document id
 * per request, there is no path by which an existing file is silently
 * replaced.
 */
export async function putDocumentObject({
  path,
  bytes,
  mimeType,
  actorId,
}: {
  readonly path: string;
  readonly bytes: Uint8Array;
  readonly mimeType: AllowedMimeType;
  readonly actorId: string;
}): Promise<boolean> {
  try {
    const admin = createSupabaseAdminClient();
    const { error } = await admin.storage.from(DOCUMENT_BUCKET).upload(
      path,
      // A fresh copy with an exact byte range, so a pooled or over-allocated
      // buffer cannot append anything to the stored object.
      bytes.slice(),
      {
        contentType: mimeType,
        upsert: false,
        // Storage will serve this back as `private, max-age=0` regardless of
        // the signed URL's lifetime (section 66).
        cacheControl: "0",
      },
    );

    if (error) {
      // The provider's message names the bucket and sometimes the key.
      logger.error("document.object_upload_failed", null, { userId: actorId });
      return false;
    }

    return true;
  } catch {
    logger.error("document.object_upload_error", null, { userId: actorId });
    return false;
  }
}

/**
 * Removes an object after the metadata write failed.
 *
 * The compensation half of section 14. It runs only on the path where the
 * row was **not** created, so it can never remove an object a document row
 * points at — there is no other delete anywhere in this feature, and the
 * database has no delete function, grant or policy at all.
 *
 * A failure here is logged and swallowed: the upload has already failed from
 * the caller's point of view, and turning a cleanup problem into a second
 * error message would tell them nothing they can act on. What it leaves is an
 * unreferenced object in a private bucket, which no policy can reach because
 * the predicate resolves an object key to a row that does not exist.
 */
export async function removeOrphanedObject(
  path: string,
  actorId: string,
): Promise<void> {
  try {
    const admin = createSupabaseAdminClient();
    const { error } = await admin.storage.from(DOCUMENT_BUCKET).remove([path]);
    if (error) {
      logger.warn("document.orphan_cleanup_failed", { userId: actorId });
    }
  } catch {
    logger.warn("document.orphan_cleanup_error", { userId: actorId });
  }
}

/**
 * A short-lived signed URL for an object the **caller** is entitled to.
 *
 * Minted with the caller's own client, so the storage policy is what decides
 * — see the note at the top of this file. The caller must have authorized the
 * document first; this is the last layer, not the only one (section 31).
 *
 * `download` sets the `Content-Disposition` filename, so the file saves under
 * the safe name the application chose rather than under whatever the uploader
 * called it (section 83).
 */
export async function createDocumentSignedUrl({
  path,
  actorId,
  downloadFileName,
}: {
  readonly path: string;
  readonly actorId: string;
  readonly downloadFileName?: string;
}): Promise<string | null> {
  try {
    const supabase = await createSupabaseServerClient();
    const { data, error } = await supabase.storage
      .from(DOCUMENT_BUCKET)
      .createSignedUrl(
        path,
        SIGNED_URL_TTL_SECONDS,
        downloadFileName ? { download: downloadFileName } : undefined,
      );

    if (error || !data?.signedUrl) {
      logger.warn("document.signed_url_failed", { userId: actorId });
      return null;
    }

    return data.signedUrl;
  } catch {
    logger.error("document.signed_url_error", null, { userId: actorId });
    return null;
  }
}
