import Link from "next/link";
import { ChevronRight } from "lucide-react";

import { cn } from "@/lib/utils/cn";

/**
 * Breadcrumbs.
 *
 * A real `<nav aria-label="Breadcrumb">` wrapping an ordered list, because
 * the order is the meaning. The final crumb is the current page: it is plain
 * text rather than a link to itself, and carries `aria-current="page"` so a
 * screen-reader user is told which one they are on.
 *
 * Separators are `aria-hidden` and generated by CSS-free markup rather than
 * by punctuation inside the link text, so the accessible name of each crumb
 * is the page name alone.
 *
 * A server component; there is nothing interactive here beyond the links.
 * Callers build the trail explicitly rather than having it inferred from the
 * pathname — an inferred trail guesses labels, and a guessed label on a
 * clinic's site is a wrong label.
 */
export interface BreadcrumbItem {
  readonly label: string;
  /** Omit on the final crumb: the current page does not link to itself. */
  readonly href?: string;
}

export interface BreadcrumbsProps {
  readonly items: readonly BreadcrumbItem[];
  readonly className?: string;
}

export function Breadcrumbs({ items, className }: BreadcrumbsProps) {
  if (items.length === 0) {
    return null;
  }

  return (
    <nav aria-label="Breadcrumb" className={className}>
      <ol className="text-body-sm text-muted-foreground flex flex-wrap items-center gap-y-1">
        {items.map((item, index) => {
          const isLast = index === items.length - 1;

          return (
            <li key={`${item.label}-${index}`} className="flex items-center">
              {index > 0 ? (
                <ChevronRight
                  aria-hidden="true"
                  className="text-border-strong mx-1 size-4 shrink-0"
                />
              ) : null}

              {item.href && !isLast ? (
                <Link
                  href={item.href}
                  className={cn(
                    // WCAG 2.2 SC 2.5.8 asks for a 24px minimum target. A
                    // breadcrumb's text is smaller than that on its own.
                    "inline-flex min-h-6 items-center",
                    "ease-natural rounded-sm transition-colors duration-(--duration-fast)",
                    "hover:text-primary underline-offset-4 hover:underline",
                    "focus-visible:outline-ring focus-visible:outline-2 focus-visible:outline-offset-2",
                  )}
                >
                  {item.label}
                </Link>
              ) : (
                <span
                  aria-current={isLast ? "page" : undefined}
                  className={cn(isLast && "text-foreground font-medium")}
                >
                  {item.label}
                </span>
              )}
            </li>
          );
        })}
      </ol>
    </nav>
  );
}
